version: "3.8"

services:
  diploma-master-core:
    build:
      context: ./
    stdin_open: true
    tty: true
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:
    driver: bridge
