name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'utility/**'
      - 'run.sh'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'utility/**'
      - 'run.sh'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: ...
